"""add_spent_field_to_kpi_tables

Revision ID: cdbb7d37ad9f
Revises: ccdc94026d58
Create Date: 2025-10-23 13:49:03.110839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cdbb7d37ad9f'
down_revision = 'ccdc94026d58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_goals', sa.Column('spent', sa.Float(), nullable=True))
    op.add_column('kpi_values', sa.Column('spent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_values', 'spent')
    op.drop_column('kpi_goals', 'spent')
    # ### end Alembic commands ###
