"""change_ad_ids_to_string

Revision ID: 3dcbe868a648
Revises: 20250126_1200
Create Date: 2025-10-27 13:06:23.413458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dcbe868a648'
down_revision = '20250126_1200'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Skip dropping message_store as it may not exist or may be in use
    op.alter_column('kpi_goals', 'ad_group_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('kpi_goals', 'ad_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('kpi_values', 'ad_group_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('kpi_values', 'ad_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi_values', 'ad_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('kpi_values', 'ad_group_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('kpi_goals', 'ad_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('kpi_goals', 'ad_group_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # Note: Skip creating message_store as it's outside this migration
    # ### end Alembic commands ###
