"""Add customer log and execution timing tables

Revision ID: add_customer_log_tables_20250917_1549
Revises: 27a6d9f5378f
Create Date: 2025-09-17T15:49:40.227596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_customer_log_tables_20250917_1549'
down_revision = '27a6d9f5378f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create customer_logs table
    op.create_table('customer_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('date_time', sa.DateTime(), nullable=False),
        sa.Column('user_intent', sa.String(), nullable=False),
        sa.Column('original_query', sa.String(), nullable=False),
        sa.Column('crewai_input_prompt', sa.String(), nullable=False),
        sa.Column('master_answer', sa.String(), nullable=False),
        sa.Column('crewai_log', sa.String(), nullable=False),
        sa.Column('total_execution_time_ms', sa.Integer(), nullable=False),
        sa.Column('timing_breakdown', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('analysis_id', sa.String(length=255), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('agents_used', sa.String(), nullable=False),
        sa.Column('tools_used', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_logs_session_id'), 'customer_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_customer_logs_date_time'), 'customer_logs', ['date_time'], unique=False)
    
    # Create execution_timings table
    op.create_table('execution_timings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('analysis_id', sa.String(length=255), nullable=True),
        sa.Column('component_type', sa.String(), nullable=False),
        sa.Column('component_name', sa.String(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('input_data', sa.String(), nullable=True),
        sa.Column('output_data', sa.String(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('parent_session_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_timings_session_id'), 'execution_timings', ['session_id'], unique=False)
    op.create_index(op.f('ix_execution_timings_analysis_id'), 'execution_timings', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_timings_analysis_id'), table_name='execution_timings')
    op.drop_index(op.f('ix_execution_timings_session_id'), table_name='execution_timings')
    op.drop_table('execution_timings')
    op.drop_index(op.f('ix_customer_logs_date_time'), table_name='customer_logs')
    op.drop_index(op.f('ix_customer_logs_session_id'), table_name='customer_logs')
    op.drop_table('customer_logs')
    # ### end Alembic commands ###
