"""Add UserPropertySelection table for storing selected properties

Revision ID: 38af7d1d67c4
Revises: d4f633c4ea26
Create Date: 2025-09-30 18:30:00.873569

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38af7d1d67c4'
down_revision = 'd4f633c4ea26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogcx_response_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogcx_response_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_log_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dialogcx_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('simplified_response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dialogcx_response_logs_pkey'))
    )
    # ### end Alembic commands ###
