"""add_dialogcx_response_log_table

Revision ID: d4f633c4ea26
Revises: aea487572365
Create Date: 2025-09-28 09:18:06.542392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4f633c4ea26'
down_revision = 'aea487572365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_execution_logs_session_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_start_time'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_task_id'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    op.alter_column('campaign_kpis', 'summary_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_campaign_kpis_campaign_id'), table_name='campaign_kpis')
    op.drop_index(op.f('ix_campaign_kpis_date'), table_name='campaign_kpis')
    op.drop_index(op.f('ix_campaign_kpis_subcustomer_id'), table_name='campaign_kpis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_kpis_subcustomer_id'), 'campaign_kpis', ['subcustomer_id'], unique=False)
    op.create_index(op.f('ix_campaign_kpis_date'), 'campaign_kpis', ['date'], unique=False)
    op.create_index(op.f('ix_campaign_kpis_campaign_id'), 'campaign_kpis', ['campaign_id'], unique=False)
    op.alter_column('campaign_kpis', 'summary_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_phase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thought', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_input', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tools_available', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tools_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_execution_logs_pkey'))
    )
    op.create_index(op.f('ix_agent_execution_logs_task_id'), 'agent_execution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_start_time'), 'agent_execution_logs', ['start_time'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_session_id'), 'agent_execution_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###
