"""Update customer fields: rename en_meta to enable_meta and add enable_google

Revision ID: 4649b62cd83f
Revises: 7d31ba632789
Create Date: 2025-10-24 17:17:59.884844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4649b62cd83f'
down_revision = '7d31ba632789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('enable_meta', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('enable_google', sa.Boolean(), nullable=True))
    op.drop_column('customers', 'en_meta')
    op.drop_constraint(op.f('fk_kpi_values_kpi_goal_id'), 'kpi_values', type_='foreignkey')
    op.create_foreign_key(None, 'kpi_values', 'kpi_goals', ['kpi_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kpi_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kpi_values_kpi_goal_id'), 'kpi_values', 'kpi_goals', ['kpi_goal_id'], ['id'], ondelete='CASCADE')
    op.add_column('customers', sa.Column('en_meta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'enable_google')
    op.drop_column('customers', 'enable_meta')
    # ### end Alembic commands ###
