"""Add campaigns table for storing campaign details

Revision ID: 20250917_103
Revises: 20250917_102
Create Date: 2025-09-17 10:32:04.436246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '20250917_103'
down_revision = '20250917_102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('digital_asset_id', sa.Integer(), nullable=False),
    sa.Column('subclient_id', sa.Integer(), nullable=False),
    sa.Column('platform_campaign_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('primary_kpi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('secondary_kpi_1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('secondary_kpi_2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('secondary_kpi_3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('landing_page_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('campaign_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['digital_asset_id'], ['digital_assets.id'], ),
    sa.ForeignKeyConstraint(['subclient_id'], ['sub_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign_mappings', sa.Column('ga4_platform_campaign_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('campaign_mappings', sa.Column('google_ads_platform_campaign_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # Use PostgreSQL USING clause for type conversion
    op.execute("ALTER TABLE campaign_mappings ALTER COLUMN ga4_campaign_id TYPE INTEGER USING ga4_campaign_id::integer")
    op.execute("ALTER TABLE campaign_mappings ALTER COLUMN google_ads_campaign_id TYPE INTEGER USING google_ads_campaign_id::integer")
    op.drop_constraint(op.f('campaign_mappings_google_ads_asset_id_fkey'), 'campaign_mappings', type_='foreignkey')
    op.drop_constraint(op.f('campaign_mappings_ga4_asset_id_fkey'), 'campaign_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_mappings', 'campaigns', ['ga4_campaign_id'], ['id'])
    op.create_foreign_key(None, 'campaign_mappings', 'campaigns', ['google_ads_campaign_id'], ['id'])
    op.drop_column('campaign_mappings', 'google_ads_asset_id')
    op.drop_column('campaign_mappings', 'campaign_name')
    op.drop_column('campaign_mappings', 'ga4_asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_mappings', sa.Column('ga4_asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campaign_mappings', sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('campaign_mappings', sa.Column('google_ads_asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'campaign_mappings', type_='foreignkey')
    op.drop_constraint(None, 'campaign_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('campaign_mappings_ga4_asset_id_fkey'), 'campaign_mappings', 'digital_assets', ['ga4_asset_id'], ['id'])
    op.create_foreign_key(op.f('campaign_mappings_google_ads_asset_id_fkey'), 'campaign_mappings', 'digital_assets', ['google_ads_asset_id'], ['id'])
    op.alter_column('campaign_mappings', 'google_ads_campaign_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('campaign_mappings', 'ga4_campaign_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('campaign_mappings', 'google_ads_platform_campaign_id')
    op.drop_column('campaign_mappings', 'ga4_platform_campaign_id')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
