"""rename_user_property_selections_columns

Revision ID: dccfef3acf23
Revises: db7b3e84453b
Create Date: 2025-10-12 11:48:00.207324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dccfef3acf23'
down_revision = 'db7b3e84453b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('created_by_campaigner_id', sa.Integer(), nullable=True))
    op.drop_column('agent_configs', 'created_by_user_id')
    op.drop_index(op.f('ix_users_email'), table_name='campaigners')
    op.create_index(op.f('ix_campaigners_email'), 'campaigners', ['email'], unique=True)
    op.drop_index(op.f('ix_info_table_composite_id'), table_name='client_info')
    op.create_index(op.f('ix_client_info_composite_id'), 'client_info', ['composite_id'], unique=True)
    op.add_column('customer_logs', sa.Column('campaigner_id', sa.Integer(), nullable=True))
    op.drop_column('customer_logs', 'user_id')
    op.add_column('questions_table', sa.Column('agency_id', sa.Integer(), nullable=False))
    op.add_column('questions_table', sa.Column('campaigner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('questions_table_customer_id_fkey'), 'questions_table', type_='foreignkey')
    op.drop_constraint(op.f('questions_table_subclient_id_fkey'), 'questions_table', type_='foreignkey')
    op.drop_constraint(op.f('questions_table_user_id_fkey'), 'questions_table', type_='foreignkey')
    op.create_foreign_key(None, 'questions_table', 'agencies', ['agency_id'], ['id'])
    op.create_foreign_key(None, 'questions_table', 'campaigners', ['campaigner_id'], ['id'])
    op.create_foreign_key(None, 'questions_table', 'customers', ['customer_id'], ['id'])
    op.drop_column('questions_table', 'user_id')
    op.drop_column('questions_table', 'subclient_id')
    op.add_column('rtm_table', sa.Column('agency_id', sa.Integer(), nullable=False))
    op.add_column('rtm_table', sa.Column('campaigner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('rtm_table_customer_id_fkey'), 'rtm_table', type_='foreignkey')
    op.drop_constraint(op.f('rtm_table_subclient_id_fkey'), 'rtm_table', type_='foreignkey')
    op.drop_constraint(op.f('rtm_table_user_id_fkey'), 'rtm_table', type_='foreignkey')
    op.create_foreign_key(None, 'rtm_table', 'campaigners', ['campaigner_id'], ['id'])
    op.create_foreign_key(None, 'rtm_table', 'agencies', ['agency_id'], ['id'])
    op.create_foreign_key(None, 'rtm_table', 'customers', ['customer_id'], ['id'])
    op.drop_column('rtm_table', 'user_id')
    op.drop_column('rtm_table', 'subclient_id')
    op.add_column('user_property_selections', sa.Column('campaigner_id', sa.Integer(), nullable=False))
    op.add_column('user_property_selections', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_property_selections_user_id_fkey'), 'user_property_selections', type_='foreignkey')
    op.drop_constraint(op.f('user_property_selections_subclient_id_fkey'), 'user_property_selections', type_='foreignkey')
    op.create_foreign_key(None, 'user_property_selections', 'campaigners', ['campaigner_id'], ['id'])
    op.create_foreign_key(None, 'user_property_selections', 'customers', ['customer_id'], ['id'])
    op.drop_column('user_property_selections', 'user_id')
    op.drop_column('user_property_selections', 'subclient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_property_selections', sa.Column('subclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_property_selections', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_property_selections', type_='foreignkey')
    op.drop_constraint(None, 'user_property_selections', type_='foreignkey')
    op.create_foreign_key(op.f('user_property_selections_subclient_id_fkey'), 'user_property_selections', 'customers', ['subclient_id'], ['id'])
    op.create_foreign_key(op.f('user_property_selections_user_id_fkey'), 'user_property_selections', 'campaigners', ['user_id'], ['id'])
    op.drop_column('user_property_selections', 'customer_id')
    op.drop_column('user_property_selections', 'campaigner_id')
    op.add_column('rtm_table', sa.Column('subclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rtm_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rtm_table', type_='foreignkey')
    op.drop_constraint(None, 'rtm_table', type_='foreignkey')
    op.drop_constraint(None, 'rtm_table', type_='foreignkey')
    op.create_foreign_key(op.f('rtm_table_user_id_fkey'), 'rtm_table', 'campaigners', ['user_id'], ['id'])
    op.create_foreign_key(op.f('rtm_table_subclient_id_fkey'), 'rtm_table', 'customers', ['subclient_id'], ['id'])
    op.create_foreign_key(op.f('rtm_table_customer_id_fkey'), 'rtm_table', 'agencies', ['customer_id'], ['id'])
    op.drop_column('rtm_table', 'campaigner_id')
    op.drop_column('rtm_table', 'agency_id')
    op.add_column('questions_table', sa.Column('subclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions_table', type_='foreignkey')
    op.drop_constraint(None, 'questions_table', type_='foreignkey')
    op.drop_constraint(None, 'questions_table', type_='foreignkey')
    op.create_foreign_key(op.f('questions_table_user_id_fkey'), 'questions_table', 'campaigners', ['user_id'], ['id'])
    op.create_foreign_key(op.f('questions_table_subclient_id_fkey'), 'questions_table', 'customers', ['subclient_id'], ['id'])
    op.create_foreign_key(op.f('questions_table_customer_id_fkey'), 'questions_table', 'agencies', ['customer_id'], ['id'])
    op.drop_column('questions_table', 'campaigner_id')
    op.drop_column('questions_table', 'agency_id')
    op.add_column('customer_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer_logs', 'campaigner_id')
    op.drop_index(op.f('ix_client_info_composite_id'), table_name='client_info')
    op.create_index(op.f('ix_info_table_composite_id'), 'client_info', ['composite_id'], unique=True)
    op.drop_index(op.f('ix_campaigners_email'), table_name='campaigners')
    op.create_index(op.f('ix_users_email'), 'campaigners', ['email'], unique=True)
    op.add_column('agent_configs', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('agent_configs', 'created_by_campaigner_id')
    # ### end Alembic commands ###
