"""update_kpi_goals_schema_remove_unused_fields

Revision ID: 8d7caaf94b4b
Revises: 6da7c6bd5862
Create Date: 2025-10-17 15:41:36.532783

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d7caaf94b4b'
down_revision = '6da7c6bd5862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_goals', sa.Column('ad_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('kpi_goals', 'campaign_num')
    op.drop_column('kpi_goals', 'date')
    op.drop_column('kpi_goals', 'weekly_budget')
    op.drop_column('kpi_goals', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_goals', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('kpi_goals', sa.Column('weekly_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_goals', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('kpi_goals', sa.Column('campaign_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('kpi_goals', 'ad_name')
    # ### end Alembic commands ###
