"""Add task allow_delegation verbose fields to agent_configs

Revision ID: 27a6d9f5378f
Revises: ddd5c9f2d002
Create Date: 2025-09-16 11:49:58.872314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27a6d9f5378f'
down_revision = 'ddd5c9f2d002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    
    # Add columns with default values first (nullable)
    op.add_column('agent_configs', sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('agent_configs', sa.Column('allow_delegation', sa.Boolean(), nullable=True, default=False))
    op.add_column('agent_configs', sa.Column('verbose', sa.Boolean(), nullable=True, default=True))
    
    # Update existing records with default values
    op.execute("UPDATE agent_configs SET allow_delegation = FALSE WHERE allow_delegation IS NULL")
    op.execute('UPDATE agent_configs SET "verbose" = TRUE WHERE "verbose" IS NULL')
    
    # Now make the columns NOT NULL
    op.alter_column('agent_configs', 'allow_delegation', nullable=False)
    op.alter_column('agent_configs', 'verbose', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'verbose')
    op.drop_column('agent_configs', 'allow_delegation')
    op.drop_column('agent_configs', 'task')
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('owner_customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    # ### end Alembic commands ###
