"""Update KpiValue model to match KpiGoal structure

Revision ID: 25cf09689f2b
Revises: 91efe70a49bb
Create Date: 2025-10-19 19:03:24.956825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25cf09689f2b'
down_revision = '91efe70a49bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invite_tokens_token_key'), 'invite_tokens', type_='unique')
    op.add_column('kpi_values', sa.Column('ad_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('kpi_values', sa.Column('primary_kpi_1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_constraint(op.f('kpi_values_kpi_goal_id_fkey'), 'kpi_values', type_='foreignkey')
    op.drop_column('kpi_values', 'date')
    op.drop_column('kpi_values', 'campaign_num')
    op.drop_column('kpi_values', 'is_active')
    op.drop_column('kpi_values', 'primary_kpi_1_unit')
    op.drop_column('kpi_values', 'secondary_kpi_3_unit')
    op.drop_column('kpi_values', 'secondary_kpi_1_unit')
    op.drop_column('kpi_values', 'measurement_date')
    op.drop_column('kpi_values', 'data_source')
    op.drop_column('kpi_values', 'secondary_kpi_1_value')
    op.drop_column('kpi_values', 'weekly_budget')
    op.drop_column('kpi_values', 'primary_kpi_1_value')
    op.drop_column('kpi_values', 'secondary_kpi_2_value')
    op.drop_column('kpi_values', 'secondary_kpi_3_value')
    op.drop_column('kpi_values', 'secondary_kpi_2_unit')
    op.drop_column('kpi_values', 'kpi_goal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_values', sa.Column('kpi_goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_2_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_3_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_2_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('primary_kpi_1_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('weekly_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_1_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('data_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('measurement_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('kpi_values', sa.Column('secondary_kpi_1_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('secondary_kpi_3_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('primary_kpi_1_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kpi_values', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('kpi_values', sa.Column('campaign_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('kpi_values', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('kpi_values_kpi_goal_id_fkey'), 'kpi_values', 'kpi_goals', ['kpi_goal_id'], ['id'])
    op.drop_column('kpi_values', 'secondary_kpi_3')
    op.drop_column('kpi_values', 'secondary_kpi_2')
    op.drop_column('kpi_values', 'secondary_kpi_1')
    op.drop_column('kpi_values', 'primary_kpi_1')
    op.drop_column('kpi_values', 'ad_name')
    op.create_unique_constraint(op.f('invite_tokens_token_key'), 'invite_tokens', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
