"""Add customer fields and audience table

Revision ID: 6de77b28dff6
Revises: caff92b1bb85
Create Date: 2025-10-22 14:34:11.775300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6de77b28dff6'
down_revision = 'caff92b1bb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_name')
    )
    op.add_column('customers', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    op.add_column('customers', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True))
    op.add_column('customers', sa.Column('en_meta', sa.String(), nullable=True))
    op.alter_column('customers', 'opening_hours',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('kpi_values', sa.Column('ad_name_headline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('kpi_values', 'ad_headline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_values', sa.Column('ad_headline', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('kpi_values', 'ad_name_headline')
    op.alter_column('customers', 'opening_hours',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('customers', 'en_meta')
    op.drop_column('customers', 'currency')
    op.drop_column('customers', 'country')
    op.drop_table('audience_table')
    # ### end Alembic commands ###
