"""Add chat_feedback table and clickup settings

Revision ID: c366e0b87911
Revises: 0ea99e96aa1d
Create Date: 2025-11-20 08:15:16.732265

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c366e0b87911'
down_revision = '0ea99e96aa1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create chat_feedback table - don't touch other tables
    op.create_table('chat_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('campaigner_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('clickup_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('clickup_task_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaigner_id'], ['campaigners.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_feedback_campaigner_id', 'chat_feedback', ['campaigner_id'], unique=False)
    op.create_index('idx_chat_feedback_created_at', 'chat_feedback', ['created_at'], unique=False)
    op.create_index('idx_chat_feedback_customer_id', 'chat_feedback', ['customer_id'], unique=False)
    op.create_index('idx_chat_feedback_message_id', 'chat_feedback', ['message_id'], unique=False)
    op.create_index('idx_chat_feedback_thread_id', 'chat_feedback', ['thread_id'], unique=False)
    op.create_index('idx_chat_feedback_type', 'chat_feedback', ['feedback_type'], unique=False)
    op.create_index('idx_chat_feedback_unique', 'chat_feedback', ['thread_id', 'message_id', 'campaigner_id'], unique=True)
    op.create_index(op.f('ix_chat_feedback_campaigner_id'), 'chat_feedback', ['campaigner_id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_customer_id'), 'chat_feedback', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_feedback_type'), 'chat_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_chat_feedback_message_id'), 'chat_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_thread_id'), 'chat_feedback', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop chat_feedback table
    op.drop_index(op.f('ix_chat_feedback_thread_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_message_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_feedback_type'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_customer_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_campaigner_id'), table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_unique', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_type', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_thread_id', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_message_id', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_customer_id', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_created_at', table_name='chat_feedback')
    op.drop_index('idx_chat_feedback_campaigner_id', table_name='chat_feedback')
    op.drop_table('chat_feedback')
    # ### end Alembic commands ###
