"""Add metrics table for campaign sync

Revision ID: 2e18477ba827
Revises: c366e0b87911
Create Date: 2025-11-20 13:16:26.836705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e18477ba827'
down_revision = 'c366e0b87911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create metrics table - don't touch other tables
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('conv_val', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('cpl', sa.Float(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['digital_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'item_id', 'platform_id', name='uq_metrics_date_item_platform')
    )
    op.create_index('idx_metrics_date', 'metrics', ['metric_date'], unique=False)
    op.create_index('idx_metrics_date_platform', 'metrics', ['metric_date', 'platform_id'], unique=False)
    op.create_index('idx_metrics_item_id', 'metrics', ['item_id'], unique=False)
    op.create_index('idx_metrics_platform_id', 'metrics', ['platform_id'], unique=False)
    op.create_index(op.f('ix_metrics_item_id'), 'metrics', ['item_id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_date'), 'metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_metrics_platform_id'), 'metrics', ['platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop metrics table
    op.drop_index(op.f('ix_metrics_platform_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_date'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_item_id'), table_name='metrics')
    op.drop_index('idx_metrics_platform_id', table_name='metrics')
    op.drop_index('idx_metrics_item_id', table_name='metrics')
    op.drop_index('idx_metrics_date_platform', table_name='metrics')
    op.drop_index('idx_metrics_date', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
