"""remove_separate_foreign_keys_from_customer_data_tables

Revision ID: 38896479ab67
Revises: a1b2c3d4e5f6
Create Date: 2025-10-12 17:43:36.316838

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '38896479ab67'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('created_by_campaigner_id', sa.Integer(), nullable=True))
    op.drop_column('agent_configs', 'created_by_user_id')
    op.drop_index(op.f('ix_users_email'), table_name='campaigners')
    op.create_index(op.f('ix_campaigners_email'), 'campaigners', ['email'], unique=True)
    op.drop_index(op.f('ix_info_table_composite_id'), table_name='client_info')
    op.create_index(op.f('ix_client_info_composite_id'), 'client_info', ['composite_id'], unique=True)
    op.drop_constraint(op.f('info_table_subclient_id_fkey'), 'client_info', type_='foreignkey')
    op.drop_constraint(op.f('info_table_customer_id_fkey'), 'client_info', type_='foreignkey')
    op.drop_constraint(op.f('info_table_user_id_fkey'), 'client_info', type_='foreignkey')
    op.drop_column('client_info', 'campaigner_id')
    op.drop_column('client_info', 'customer_id')
    op.drop_column('client_info', 'agency_id')
    op.add_column('customer_logs', sa.Column('campaigner_id', sa.Integer(), nullable=True))
    op.drop_column('customer_logs', 'user_id')
    op.drop_constraint(op.f('questions_table_customer_id_fkey'), 'questions_table', type_='foreignkey')
    op.drop_constraint(op.f('questions_table_subclient_id_fkey'), 'questions_table', type_='foreignkey')
    op.drop_constraint(op.f('questions_table_user_id_fkey'), 'questions_table', type_='foreignkey')
    op.drop_column('questions_table', 'user_id')
    op.drop_column('questions_table', 'customer_id')
    op.drop_column('questions_table', 'subclient_id')
    op.drop_constraint(op.f('rtm_table_customer_id_fkey'), 'rtm_table', type_='foreignkey')
    op.drop_constraint(op.f('rtm_table_subclient_id_fkey'), 'rtm_table', type_='foreignkey')
    op.drop_constraint(op.f('rtm_table_user_id_fkey'), 'rtm_table', type_='foreignkey')
    op.drop_column('rtm_table', 'user_id')
    op.drop_column('rtm_table', 'customer_id')
    op.drop_column('rtm_table', 'subclient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rtm_table', sa.Column('subclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rtm_table', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rtm_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rtm_table_user_id_fkey'), 'rtm_table', 'campaigners', ['user_id'], ['id'])
    op.create_foreign_key(op.f('rtm_table_subclient_id_fkey'), 'rtm_table', 'customers', ['subclient_id'], ['id'])
    op.create_foreign_key(op.f('rtm_table_customer_id_fkey'), 'rtm_table', 'agencies', ['customer_id'], ['id'])
    op.add_column('questions_table', sa.Column('subclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions_table', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('questions_table_user_id_fkey'), 'questions_table', 'campaigners', ['user_id'], ['id'])
    op.create_foreign_key(op.f('questions_table_subclient_id_fkey'), 'questions_table', 'customers', ['subclient_id'], ['id'])
    op.create_foreign_key(op.f('questions_table_customer_id_fkey'), 'questions_table', 'agencies', ['customer_id'], ['id'])
    op.add_column('customer_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer_logs', 'campaigner_id')
    op.add_column('client_info', sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('client_info', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('client_info', sa.Column('campaigner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('info_table_user_id_fkey'), 'client_info', 'campaigners', ['campaigner_id'], ['id'])
    op.create_foreign_key(op.f('info_table_customer_id_fkey'), 'client_info', 'agencies', ['agency_id'], ['id'])
    op.create_foreign_key(op.f('info_table_subclient_id_fkey'), 'client_info', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_client_info_composite_id'), table_name='client_info')
    op.create_index(op.f('ix_info_table_composite_id'), 'client_info', ['composite_id'], unique=True)
    op.drop_index(op.f('ix_campaigners_email'), table_name='campaigners')
    op.create_index(op.f('ix_users_email'), 'campaigners', ['email'], unique=True)
    op.add_column('agent_configs', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('agent_configs', 'created_by_campaigner_id')
    # ### end Alembic commands ###
